# Load data

In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_json(
    '../data/raw/shopee_reviews_dataset.jsonl',
    lines=True
)
df.head()

,id,review,rating,label
0,74263765409,Hương vị:thom Chắc do bên giao hàng bị vỡ mấy...,3,negative
1,11104151002,Hương thơm:nhẹ nhàng Lợi ích:phục hồi cấp ẩm M...,5,positive
2,15888299382,Chất lượng sản phẩm:ok Đúng với mô tả:đúng Lầ...,5,positive
3,81030214453,Độ tuổi sử dụng:em bes Chất lượng sản phẩm:tot...,5,positive
4,88484377297,"Hương vị:Mix vị, Tím Mình mua 64 gói (32 gói ...",1,negative

In [19]:
print(df.shape)
print(df.info())

(9599, 4)
<class 'pandas.DataFrame'>
RangeIndex: 9599 entries, 0 to 9598
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      9599 non-null   int64
 1   review  9599 non-null   str
 2   rating  9599 non-null   int64
 3   label   9599 non-null   str
dtypes: int64(2), str(2)
memory usage: 2.0 MB
None

In [20]:
df_unaccented = pd.read_json(
    '../data/raw/aug_unaccented_reviews.jsonl',
    lines=True
)
df_unaccented.head()

,id,review,rating,label
0,59241444271,"Mui huong:Ngot nhe, thomm Phu hop voi loai da:...",4,positive
1,75292434640,Toi rat hai long voi dich vu cua nguoi ban va ...,5,positive
2,13364343551,Review nhe mot so dong sua con uong tang can t...,5,positive
3,84816190204,"Hieu qua:Sach Thiet ke:Dep Thiet ke nho gon, ...",5,positive
4,30102564756,"Giao hang nhanh, dong goi dep an toan Mui Pink...",4,positive

In [21]:
print(df_unaccented.shape)
print(df_unaccented.info())

(1348, 4)
<class 'pandas.DataFrame'>
RangeIndex: 1348 entries, 0 to 1347
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1348 non-null   int64
 1   review  1348 non-null   str
 2   rating  1348 non-null   int64
 3   label   1348 non-null   str
dtypes: int64(2), str(2)
memory usage: 465.0 KB
None

In [22]:
print("NA counts:\n", df.isna().sum())
print("NA counts:\n", df_unaccented.isna().sum())

NA counts:
 id        0
review    0
rating    0
label     0
dtype: int64
NA counts:
 id        0
review    0
rating    0
label     0
dtype: int64

# Clean text

In [23]:
import re
import string

# syntax: re.sub(pattern, replace, text)
# find pattern and replace with 'replace'
# r"..." is raw string
# \S means character that  is not whitespace
# .*? means all characters
def remove_url(text):
    return re.sub(r"http\S+|www\S+", "", text)

def remove_html(text):
    return re.sub(r"<.*?>", "", text)

def remove_punctuation(text):
    return re.sub(r'[^\w\s]', ' ', text)
    # delete all punctuations

def remove_special_characters(text):
    return re.sub(r"[^a-zA-ZÀ-ỹ0-9\s]", "", text)

def normalize_whitespace(text):
    return re.sub(r"\s+", " ", text).strip()
    # turn consecutive whitespaces into one, remove begin/end whitespace

def clean_text(text):
    text = text.lower()
    text = remove_url(text)
    text = remove_html(text)
    text = remove_punctuation(text)
    text = remove_special_characters(text)
    text = normalize_whitespace(text)

    return text

In [24]:
df["clean_review"] = df["review"].apply(clean_text)
display(df.loc[0, "review"])
display(df["clean_review"])

'Hương vị:thom  Chắc do bên giao hàng bị vỡ mấy gói'

0       hương vị thom chắc do bên giao hàng bị vỡ mấy gói
1       hương thơm nhẹ nhàng lợi ích phục hồi cấp ẩm m...
2       chất lượng sản phẩm ok đúng với mô tả đúng lần...
3       độ tuổi sử dụng em bes chất lượng sản phẩm tot...
4       hương vị mix vị tím mình mua 64 gói 32 gói mix...
                              ...
9594    minh co huy đơn ma shop ko huy va đong luon 2 ...
9595    hương thơm thơm mẹo k có bao bì đẹp0 vẫn rụng ...
9596    không có tặng phẩm kèm như trên hình quảng cáo...
9597    bao bì mẫu mã mi nh đa nhâ n đươ c ha ng đo ng...
9598    kem từ bao bì đến chất lượng bên trong thấy đề...
Name: clean_review, Length: 9599, dtype: str

In [25]:
df_unaccented["clean_review"] = df_unaccented["review"].apply(clean_text)
display(df_unaccented.loc[0,"review"])
display(df_unaccented["clean_review"])

'Mui huong:Ngot nhe, thomm Phu hop voi loai da:minh nghi la moi loai da Cong dung:duong trang nhung ma ch thay trang chi thay thom nhe  Helu mn, minh feeedback dayy. Minh nghi ai cung muon co loi khuyen that long, vay minh se co gang de mieu ta trai nghiem nhe. Minh thu nghiem trong mot tuan, co ket hop ca scrub body dove tu unilever loai sakura luon. Sau thi minh thay hien tai no chi thom la chinh, da minh cung deu mau hon nhung ma mau ngam ngam . Um minh nghi ve phan duong trang thi kbt tnao nhung minh nghi kh qua hieu qua. Tu hinh anh ban thay da minh truoc va sau day. Minh co cai vong thi n cung che nang phan nao nhung ma cam giac da de bat nang lam. Ngu day phong he he anh sang ma cam giac da ngam hon roi hic khong biet co phai do minh khong. Minh van boi KCN MOI NGAY NHE. Minh boi kha day, dung loai senka duong am cong them ca ao chong nang ma van ngam. Mn biet s cach nao huong dan minh trang hon voi hic. Thi day la trai nghiem cua minh. Them nua muon nhan qua moi nguoi phai an du qua trong gio nhe. NHO AN DUU!! A voi ca rcm xem phim materialist. KH PR DAU nhma n hay that. Camon mn <33'

0       mui huong ngot nhe thomm phu hop voi loai da m...
1       toi rat hai long voi dich vu cua nguoi ban va ...
2       review nhe mot so dong sua con uong tang can t...
3       hieu qua sach thiet ke dep thiet ke nho gon ti...
4       giao hang nhanh dong goi dep an toan mui pink ...
                              ...
1343    kiem soat dau toc bet da man bet lam sach cong...
1344    truoc gio xai kcn khac ko sao nay boi thu loai...
1345    minh bi di ung rat nhieu sua tam nen chi dung ...
1346    ua sao thay co qua tang ma mo ra thi ko co sho...
1347          gia sp cao hon ca gia ngoai du ap ma ao gia
Name: clean_review, Length: 1348, dtype: str

# Normalize_text

From this step forward, the unaccented reviews CAN'T be processed the same way with accented ones. It is really hard and may be out of scope to try to give diatritic to those unaccented reviews.

In [40]:
df.loc[1, "review"]

'Hương thơm:nhẹ nhàng Lợi ích:phục hồi cấp ẩm Mẹo:không có  Shop đóng gói cẩn thận chu đáo lắm Ship nhanh  Shiper thân thiện Sẽ ủng hộ tiếp tục nha  Tks'

In [57]:
df.loc[3405, "review"]

'Giao hàng nhanh. Mua giá rẻ hơn siêu thị. Giao đủ số lượng. Đóng gói cẩn thận.'

In [28]:
import unicodedata

SLANG_DICT = {
    "ko": "không",
    "khum": "không",
    "hok": "không",
    "k": "không",
    "dc": "được",
    "mn": "mọi người",
    "ntn": "như thế nào",
    "sp": "sản phẩm"
}
def normalize_unicode(text):
    return unicodedata.normalize("NFC", text)

def normalize_slang(text):
    words = text.split()
    norm_words = []
    for word in words:
        norm_words.append(SLANG_DICT.get(word, word))
        # replace if it's a slang
    return " ".join(norm_words)

def normalize_repeated_characters(text):
    return re.sub(r"(.)\1+", r"\1", text)

def normalize_text(text):
    text = normalize_unicode(text)
    text = normalize_slang(text)
    text = normalize_repeated_characters(text)

    return text

In [30]:
df["normalized_review"] = df["clean_review"].apply(normalize_text)
display(df.loc[1:5, "clean_review"])
display(df["normalized_review"])

1    hương thơm nhẹ nhàng lợi ích phục hồi cấp ẩm m...
2    chất lượng sản phẩm ok đúng với mô tả đúng lần...
3    độ tuổi sử dụng em bes chất lượng sản phẩm tot...
4    hương vị mix vị tím mình mua 64 gói 32 gói mix...
5               hàng đặt sữa uống mà giao hàng 15 ngày
Name: clean_review, dtype: str

0       hương vị thom chắc do bên giao hàng bị vỡ mấy gói
1       hương thơm nhẹ nhàng lợi ích phục hồi cấp ẩm m...
2       chất lượng sản phẩm ok đúng với mô tả đúng lần...
3       độ tuổi sử dụng em bes chất lượng sản phẩm tot...
4       hương vị mix vị tím mình mua 64 gói 32 gói mix...
                              ...
9594    minh co huy đơn ma shop không huy va đong luon...
9595    hương thơm thơm mẹo không có bao bì đẹp0 vẫn r...
9596    không có tặng phẩm kèm như trên hình quảng cáo...
9597    bao bì mẫu mã mi nh đa nhâ n đươ c ha ng đo ng...
9598    kem từ bao bì đến chất lượng bên trong thấy đề...
Name: normalized_review, Length: 9599, dtype: str

# Word_segmentation

In this step, we define what is a correct word to preserve the meaning of words. This step is critical because Vietnamese word is not word by word separated by spaces, but a combination, for example "hoc sinh" not "hoc" and "sinh". We have 2 libraries to help with this.

In [31]:
from underthesea import word_tokenize
from pyvi.ViTokenizer import tokenize

def segment_underthesea(text):
    return word_tokenize(text, format="text")
    # segment and return a string (format="text")

def segment_pyvi(text):
    return tokenize(text)

def segment_text(text, method="underthesea"):
    if method == "underthesea":
        return segment_underthesea(text)
    elif method == "pyvi":
        return segment_pyvi(text)
    else:
        raise ValueError("Invalid segmentation method")

In [32]:
df["segmented_review"] = df["normalized_review"].apply(segment_pyvi)
display(df.loc[1:5, "normalized_review"])
display(df["segmented_review"])

1    hương thơm nhẹ nhàng lợi ích phục hồi cấp ẩm m...
2    chất lượng sản phẩm ok đúng với mô tả đúng lần...
3    độ tuổi sử dụng em bes chất lượng sản phẩm tot...
4    hương vị mix vị tím mình mua 64 gói 32 gói mix...
5               hàng đặt sữa uống mà giao hàng 15 ngày
Name: normalized_review, dtype: str

0       hương_vị thom chắc do bên giao hàng bị vỡ mấy gói
1       hương thơm nhẹ_nhàng lợi_ích phục_hồi cấp ẩm m...
2       chất_lượng sản_phẩm ok đúng với mô_tả đúng lần...
3       độ tuổi sử_dụng em bes chất_lượng sản_phẩm tot...
4       hương_vị mix vị tím mình mua 64 gói 32 gói mix...
                              ...
9594    minh co huy đơn ma shop không huy va đong luon...
9595    hương thơm thơm mẹo không có bao_bì đẹp0 vẫn r...
9596    không có tặng_phẩm kèm như trên hình quảng_cáo...
9597    bao_bì mẫu_mã mi nh đa nhâ n đươ c ha ng đo ng...
9598    kem từ bao_bì đến chất_lượng bên trong thấy đề...
Name: segmented_review, Length: 9599, dtype: str

# Tokenize

TF-IDF is used for ML. PhoBERT is used for DL like LSTM. This is where ML and DL pipeline sets apart. Tokenization returns a sparse matrix or tensor, not normal vector or dataframe type.

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import AutoTokenizer

def tokenize_tfidf(tokenizer, texts):
    return tokenizer.fit_transform(texts)

def phobert_tokenizer():
    return AutoTokenizer.from_pretrained("vinai/phobert-base")

def tokenize_phobert(tokenizer, text):
    return tokenizer(text, padding="max_length", # force all sequences to have the same length
                     truncation=True, # truncate if token too long
                     max_length=128, return_tensor="pt") # return pytorch tensor

In [38]:
tfidf = TfidfVectorizer()
tokens_ML = tokenize_tfidf(tfidf, df["segmented_review"])
tokens_ML

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 215982 stored elements and shape (9599, 8663)>

In [39]:
phobert = phobert_tokenizer()
tokens_DL = df["segmented_review"].apply(
    lambda x: tokenize_phobert(phobert, x)
)
tokens_DL

0       {'input_ids': [0, 4088, 5642, 599, 1508, 91, 1...
1       {'input_ids': [0, 2263, 2023, 2410, 1205, 2646...
2       {'input_ids': [0, 390, 265, 11685, 287, 15, 11...
3       {'input_ids': [0, 378, 126, 117, 193, 43081, 3...
4       {'input_ids': [0, 4088, 9889, 626, 3702, 68, 1...
                              ...
9594    {'input_ids': [0, 9534, 3005, 23250, 807, 2006...
9595    {'input_ids': [0, 2263, 2023, 2023, 7716, 17, ...
9596    {'input_ids': [0, 17, 10, 53359, 3884, 1171, 4...
9597    {'input_ids': [0, 7309, 9726, 5659, 5976, 2529...
9598    {'input_ids': [0, 2771, 39, 7309, 30, 390, 145...
Name: segmented_review, Length: 9599, dtype: object